#Zad3
def Ulice():
    ulice = ["Jagodowa", "Lipowa", "Kwiatowa", "Kasztanowa", "Polna"]   #Lista ulic

    for u in ulice:                 #Petla dla ulic
        for b in range(5):          #Petla dla blokow
            for l in range(10):     #Petla dla lokali
                print(f"Ulica: {u}, Blok:{b+1}, Lokal: {l+1}")          #Wypisywanie danej ulicy, bloku, lokalu w kazdym przypadku wykanania petli

Ulice()


'''
Ulica: Jagodowa, Blok:1, Lokal: 1
Ulica: Jagodowa, Blok:1, Lokal: 2
Ulica: Jagodowa, Blok:1, Lokal: 3
Ulica: Jagodowa, Blok:1, Lokal: 4
Ulica: Jagodowa, Blok:1, Lokal: 5
Ulica: Jagodowa, Blok:1, Lokal: 6
Ulica: Jagodowa, Blok:1, Lokal: 7
Ulica: Jagodowa, Blok:1, Lokal: 8
Ulica: Jagodowa, Blok:1, Lokal: 9
Ulica: Jagodowa, Blok:1, Lokal: 10
Ulica: Jagodowa, Blok:2, Lokal: 1
Ulica: Jagodowa, Blok:2, Lokal: 2
Ulica: Jagodowa, Blok:2, Lokal: 3
Ulica: Jagodowa, Blok:2, Lokal: 4
Ulica: Jagodowa, Blok:2, Lokal: 5
Ulica: Jagodowa, Blok:2, Lokal: 6
Ulica: Jagodowa, Blok:2, Lokal: 7
Ulica: Jagodowa, Blok:2, Lokal: 8
Ulica: Jagodowa, Blok:2, Lokal: 9
Ulica: Jagodowa, Blok:2, Lokal: 10
Ulica: Jagodowa, Blok:3, Lokal: 1
Ulica: Jagodowa, Blok:3, Lokal: 2
Ulica: Jagodowa, Blok:3, Lokal: 3
Ulica: Jagodowa, Blok:3, Lokal: 4
Ulica: Jagodowa, Blok:3, Lokal: 5
Ulica: Jagodowa, Blok:3, Lokal: 6
Ulica: Jagodowa, Blok:3, Lokal: 7
Ulica: Jagodowa, Blok:3, Lokal: 8
Ulica: Jagodowa, Blok:3, Lokal: 9
Ulica: Jagodowa, Blok:3, Lokal: 10
Ulica: Jagodowa, Blok:4, Lokal: 1
Ulica: Jagodowa, Blok:4, Lokal: 2
Ulica: Jagodowa, Blok:4, Lokal: 3
Ulica: Jagodowa, Blok:4, Lokal: 4
Ulica: Jagodowa, Blok:4, Lokal: 5
Ulica: Jagodowa, Blok:4, Lokal: 6
Ulica: Jagodowa, Blok:4, Lokal: 7
Ulica: Jagodowa, Blok:4, Lokal: 8
Ulica: Jagodowa, Blok:4, Lokal: 9
Ulica: Jagodowa, Blok:4, Lokal: 10
Ulica: Jagodowa, Blok:5, Lokal: 1
Ulica: Jagodowa, Blok:5, Lokal: 2
Ulica: Jagodowa, Blok:5, Lokal: 3
Ulica: Jagodowa, Blok:5, Lokal: 4
Ulica: Jagodowa, Blok:5, Lokal: 5
Ulica: Jagodowa, Blok:5, Lokal: 6
Ulica: Jagodowa, Blok:5, Lokal: 7
Ulica: Jagodowa, Blok:5, Lokal: 8
Ulica: Jagodowa, Blok:5, Lokal: 9
Ulica: Jagodowa, Blok:5, Lokal: 10
Ulica: Lipowa, Blok:1, Lokal: 1
Ulica: Lipowa, Blok:1, Lokal: 2
Ulica: Lipowa, Blok:1, Lokal: 3
Ulica: Lipowa, Blok:1, Lokal: 4
Ulica: Lipowa, Blok:1, Lokal: 5
Ulica: Lipowa, Blok:1, Lokal: 6
Ulica: Lipowa, Blok:1, Lokal: 7
Ulica: Lipowa, Blok:1, Lokal: 8
Ulica: Lipowa, Blok:1, Lokal: 9
Ulica: Lipowa, Blok:1, Lokal: 10
Ulica: Lipowa, Blok:2, Lokal: 1
Ulica: Lipowa, Blok:2, Lokal: 2
Ulica: Lipowa, Blok:2, Lokal: 3
Ulica: Lipowa, Blok:2, Lokal: 4
Ulica: Lipowa, Blok:2, Lokal: 5
Ulica: Lipowa, Blok:2, Lokal: 6
Ulica: Lipowa, Blok:2, Lokal: 7
Ulica: Lipowa, Blok:2, Lokal: 8
Ulica: Lipowa, Blok:2, Lokal: 9
Ulica: Lipowa, Blok:2, Lokal: 10
Ulica: Lipowa, Blok:3, Lokal: 1
Ulica: Lipowa, Blok:3, Lokal: 2
Ulica: Lipowa, Blok:3, Lokal: 3
Ulica: Lipowa, Blok:3, Lokal: 4
Ulica: Lipowa, Blok:3, Lokal: 5
Ulica: Lipowa, Blok:3, Lokal: 6
Ulica: Lipowa, Blok:3, Lokal: 7
Ulica: Lipowa, Blok:3, Lokal: 8
Ulica: Lipowa, Blok:3, Lokal: 9
Ulica: Lipowa, Blok:3, Lokal: 10
Ulica: Lipowa, Blok:4, Lokal: 1
Ulica: Lipowa, Blok:4, Lokal: 2
Ulica: Lipowa, Blok:4, Lokal: 3
Ulica: Lipowa, Blok:4, Lokal: 4
Ulica: Lipowa, Blok:4, Lokal: 5
Ulica: Lipowa, Blok:4, Lokal: 6
Ulica: Lipowa, Blok:4, Lokal: 7
Ulica: Lipowa, Blok:4, Lokal: 8
Ulica: Lipowa, Blok:4, Lokal: 9
Ulica: Lipowa, Blok:4, Lokal: 10
Ulica: Lipowa, Blok:5, Lokal: 1
Ulica: Lipowa, Blok:5, Lokal: 2
Ulica: Lipowa, Blok:5, Lokal: 3
Ulica: Lipowa, Blok:5, Lokal: 4
Ulica: Lipowa, Blok:5, Lokal: 5
Ulica: Lipowa, Blok:5, Lokal: 6
Ulica: Lipowa, Blok:5, Lokal: 7
Ulica: Lipowa, Blok:5, Lokal: 8
Ulica: Lipowa, Blok:5, Lokal: 9
Ulica: Lipowa, Blok:5, Lokal: 10
Ulica: Kwiatowa, Blok:1, Lokal: 1
Ulica: Kwiatowa, Blok:1, Lokal: 2
Ulica: Kwiatowa, Blok:1, Lokal: 3
Ulica: Kwiatowa, Blok:1, Lokal: 4
Ulica: Kwiatowa, Blok:1, Lokal: 5
Ulica: Kwiatowa, Blok:1, Lokal: 6
Ulica: Kwiatowa, Blok:1, Lokal: 7
Ulica: Kwiatowa, Blok:1, Lokal: 8
Ulica: Kwiatowa, Blok:1, Lokal: 9
Ulica: Kwiatowa, Blok:1, Lokal: 10
Ulica: Kwiatowa, Blok:2, Lokal: 1
Ulica: Kwiatowa, Blok:2, Lokal: 2
Ulica: Kwiatowa, Blok:2, Lokal: 3
Ulica: Kwiatowa, Blok:2, Lokal: 4
Ulica: Kwiatowa, Blok:2, Lokal: 5
Ulica: Kwiatowa, Blok:2, Lokal: 6
Ulica: Kwiatowa, Blok:2, Lokal: 7
Ulica: Kwiatowa, Blok:2, Lokal: 8
Ulica: Kwiatowa, Blok:2, Lokal: 9
Ulica: Kwiatowa, Blok:2, Lokal: 10
Ulica: Kwiatowa, Blok:3, Lokal: 1
Ulica: Kwiatowa, Blok:3, Lokal: 2
Ulica: Kwiatowa, Blok:3, Lokal: 3
Ulica: Kwiatowa, Blok:3, Lokal: 4
Ulica: Kwiatowa, Blok:3, Lokal: 5
Ulica: Kwiatowa, Blok:3, Lokal: 6
Ulica: Kwiatowa, Blok:3, Lokal: 7
Ulica: Kwiatowa, Blok:3, Lokal: 8
Ulica: Kwiatowa, Blok:3, Lokal: 9
Ulica: Kwiatowa, Blok:3, Lokal: 10
Ulica: Kwiatowa, Blok:4, Lokal: 1
Ulica: Kwiatowa, Blok:4, Lokal: 2
Ulica: Kwiatowa, Blok:4, Lokal: 3
Ulica: Kwiatowa, Blok:4, Lokal: 4
Ulica: Kwiatowa, Blok:4, Lokal: 5
Ulica: Kwiatowa, Blok:4, Lokal: 6
Ulica: Kwiatowa, Blok:4, Lokal: 7
Ulica: Kwiatowa, Blok:4, Lokal: 8
Ulica: Kwiatowa, Blok:4, Lokal: 9
Ulica: Kwiatowa, Blok:4, Lokal: 10
Ulica: Kwiatowa, Blok:5, Lokal: 1
Ulica: Kwiatowa, Blok:5, Lokal: 2
Ulica: Kwiatowa, Blok:5, Lokal: 3
Ulica: Kwiatowa, Blok:5, Lokal: 4
Ulica: Kwiatowa, Blok:5, Lokal: 5
Ulica: Kwiatowa, Blok:5, Lokal: 6
Ulica: Kwiatowa, Blok:5, Lokal: 7
Ulica: Kwiatowa, Blok:5, Lokal: 8
Ulica: Kwiatowa, Blok:5, Lokal: 9
Ulica: Kwiatowa, Blok:5, Lokal: 10
Ulica: Kasztanowa, Blok:1, Lokal: 1
Ulica: Kasztanowa, Blok:1, Lokal: 2
Ulica: Kasztanowa, Blok:1, Lokal: 3
Ulica: Kasztanowa, Blok:1, Lokal: 4
Ulica: Kasztanowa, Blok:1, Lokal: 5
Ulica: Kasztanowa, Blok:1, Lokal: 6
Ulica: Kasztanowa, Blok:1, Lokal: 7
Ulica: Kasztanowa, Blok:1, Lokal: 8
Ulica: Kasztanowa, Blok:1, Lokal: 9
Ulica: Kasztanowa, Blok:1, Lokal: 10
Ulica: Kasztanowa, Blok:2, Lokal: 1
Ulica: Kasztanowa, Blok:2, Lokal: 2
Ulica: Kasztanowa, Blok:2, Lokal: 3
Ulica: Kasztanowa, Blok:2, Lokal: 4
Ulica: Kasztanowa, Blok:2, Lokal: 5
Ulica: Kasztanowa, Blok:2, Lokal: 6
Ulica: Kasztanowa, Blok:2, Lokal: 7
Ulica: Kasztanowa, Blok:2, Lokal: 8
Ulica: Kasztanowa, Blok:2, Lokal: 9
Ulica: Kasztanowa, Blok:2, Lokal: 10
Ulica: Kasztanowa, Blok:3, Lokal: 1
Ulica: Kasztanowa, Blok:3, Lokal: 2
Ulica: Kasztanowa, Blok:3, Lokal: 3
Ulica: Kasztanowa, Blok:3, Lokal: 4
Ulica: Kasztanowa, Blok:3, Lokal: 5
Ulica: Kasztanowa, Blok:3, Lokal: 6
Ulica: Kasztanowa, Blok:3, Lokal: 7
Ulica: Kasztanowa, Blok:3, Lokal: 8
Ulica: Kasztanowa, Blok:3, Lokal: 9
Ulica: Kasztanowa, Blok:3, Lokal: 10
Ulica: Kasztanowa, Blok:4, Lokal: 1
Ulica: Kasztanowa, Blok:4, Lokal: 2
Ulica: Kasztanowa, Blok:4, Lokal: 3
Ulica: Kasztanowa, Blok:4, Lokal: 4
Ulica: Kasztanowa, Blok:4, Lokal: 5
Ulica: Kasztanowa, Blok:4, Lokal: 6
Ulica: Kasztanowa, Blok:4, Lokal: 7
Ulica: Kasztanowa, Blok:4, Lokal: 8
Ulica: Kasztanowa, Blok:4, Lokal: 9
Ulica: Kasztanowa, Blok:4, Lokal: 10
Ulica: Kasztanowa, Blok:5, Lokal: 1
Ulica: Kasztanowa, Blok:5, Lokal: 2
Ulica: Kasztanowa, Blok:5, Lokal: 3
Ulica: Kasztanowa, Blok:5, Lokal: 4
Ulica: Kasztanowa, Blok:5, Lokal: 5
Ulica: Kasztanowa, Blok:5, Lokal: 6
Ulica: Kasztanowa, Blok:5, Lokal: 7
Ulica: Kasztanowa, Blok:5, Lokal: 8
Ulica: Kasztanowa, Blok:5, Lokal: 9
Ulica: Kasztanowa, Blok:5, Lokal: 10
Ulica: Polna, Blok:1, Lokal: 1
Ulica: Polna, Blok:1, Lokal: 2
Ulica: Polna, Blok:1, Lokal: 3
Ulica: Polna, Blok:1, Lokal: 4
Ulica: Polna, Blok:1, Lokal: 5
Ulica: Polna, Blok:1, Lokal: 6
Ulica: Polna, Blok:1, Lokal: 7
Ulica: Polna, Blok:1, Lokal: 8
Ulica: Polna, Blok:1, Lokal: 9
Ulica: Polna, Blok:1, Lokal: 10
Ulica: Polna, Blok:2, Lokal: 1
Ulica: Polna, Blok:2, Lokal: 2
Ulica: Polna, Blok:2, Lokal: 3
Ulica: Polna, Blok:2, Lokal: 4
Ulica: Polna, Blok:2, Lokal: 5
Ulica: Polna, Blok:2, Lokal: 6
Ulica: Polna, Blok:2, Lokal: 7
Ulica: Polna, Blok:2, Lokal: 8
Ulica: Polna, Blok:2, Lokal: 9
Ulica: Polna, Blok:2, Lokal: 10
Ulica: Polna, Blok:3, Lokal: 1
Ulica: Polna, Blok:3, Lokal: 2
Ulica: Polna, Blok:3, Lokal: 3
Ulica: Polna, Blok:3, Lokal: 4
Ulica: Polna, Blok:3, Lokal: 5
Ulica: Polna, Blok:3, Lokal: 6
Ulica: Polna, Blok:3, Lokal: 7
Ulica: Polna, Blok:3, Lokal: 8
Ulica: Polna, Blok:3, Lokal: 9
Ulica: Polna, Blok:3, Lokal: 10
Ulica: Polna, Blok:4, Lokal: 1
Ulica: Polna, Blok:4, Lokal: 2
Ulica: Polna, Blok:4, Lokal: 3
Ulica: Polna, Blok:4, Lokal: 4
Ulica: Polna, Blok:4, Lokal: 5
Ulica: Polna, Blok:4, Lokal: 6
Ulica: Polna, Blok:4, Lokal: 7
Ulica: Polna, Blok:4, Lokal: 8
Ulica: Polna, Blok:4, Lokal: 9
Ulica: Polna, Blok:4, Lokal: 10
Ulica: Polna, Blok:5, Lokal: 1
Ulica: Polna, Blok:5, Lokal: 2
Ulica: Polna, Blok:5, Lokal: 3
Ulica: Polna, Blok:5, Lokal: 4
Ulica: Polna, Blok:5, Lokal: 5
Ulica: Polna, Blok:5, Lokal: 6
Ulica: Polna, Blok:5, Lokal: 7
Ulica: Polna, Blok:5, Lokal: 8
Ulica: Polna, Blok:5, Lokal: 9
Ulica: Polna, Blok:5, Lokal: 10
'''